version: "3.4"  # compose file version
services:
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
    restart: unless-stopped
    networks:
      - hissenet
    environment:
      TZ: "Europe/Istanbul"
    logging:
      options:
        max-size: 10m

  elasticsearch:
    image: elasticsearch:7.14.1
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped
    networks:
      - hissenet
    environment:
      TZ: "Europe/Istanbul"
      discovery: "type=single-node"
    logging:
      options:
        max-size: 10m

  kibana:
    image: kibana:7.14.1
    ports:
      - "5601:5601"
    restart: unless-stopped
    networks:
      - hissenet
    environment:
      TZ: "Europe/Istanbul"
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    logging:
      options:
        max-size: 10m

networks:
  hissenet:

volumes:
  hissevol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/app'
