apiVersion: v1
kind: Service
metadata:
  labels:
    app: elastic-deploy
  name: elasticsearch
spec:
  ports:
  - port: 9200
  selector:
    app: elastic-deploy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elastic-deploy
  name: elastic-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-deploy
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: elastic-deploy
    spec:
      containers:
      - image: elasticsearch:7.14.1
        name: elasticsearch
        env:
          - name: discovery.type
            value: "single-node"
        ports:
        - containerPort: 9200

