apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq-queue
  name: rabbitmq
spec:
  ports:
  - port: 5672
  selector:
    app: rabbitmq-queue

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-queue
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: rabbitmq-queue
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        ports:
        - containerPort: 5672
